---
- name: Update apt cache
  apt: update_cache=yes

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Download Vault
  get_url:
    url: "https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_amd64.zip"
    dest: "/tmp/vault.zip"

- name: Unzip Vault
  unarchive:
    src: "/tmp/vault.zip"
    dest: "/usr/local/bin/"
    remote_src: yes

- name: Give Vault executable permissions
  file:
    path: "/usr/local/bin/vault"
    mode: "0755"

- name: Copy Vault configuration file
  copy:
    src: "{{ playbook_dir }}/../../vault_config/vault.hcl"
    dest: "/etc/vault.hcl"
    mode: "0644"

- name: Create Vault service file
  copy:
    content: |
      [Unit]
      Description="HashiCorp Vault - A tool for managing secrets"
      Documentation=https://www.vaultproject.io/docs/
      [Service]
      ExecStart=/usr/local/bin/vault server -config=/etc/vault.hcl
      ExecReload=/bin/kill --signal HUP $MAINPID
      KillMode=process
      Restart=on-failure
      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/vault.service"

- name: Reload systemd
  systemd: daemon_reload=yes

- name: Enable and start Vault service
  systemd:
    name: vault
    enabled: yes
    state: started

